### ISSUE TITLE
Failed build at 10.13.3

### ISSUE THREAD

**Issue by pavelponomarev** [ElmerCSC/homebrew-elmerfem#9]
Build failed with the following message
```
pavel$ brew install elmer
Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/elmercsc/homebrew-elmerfem/elmer.rb:22:in `<class:Elmer>'
Please report this to the elmercsc/elmerfem tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/elmercsc/homebrew-elmerfem/elmer.rb:25:in `<class:Elmer>'
Please report this to the elmercsc/elmerfem tap!
```

**Comment by leTrice** [comment]
In the meantime the deprecation warning is an error now.
```
mbp$ brew doctor
Error: Calling 'depends_on :mpi' is disabled!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/elmercsc/homebrew-elmerfem/elmer.rb:22:in `<class:Elmer>'
Please report this to the elmercsc/elmerfem tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/elmercsc/homebrew-elmerfem/issues
```

Just created a [pull request](https://github.com/ElmerCSC/homebrew-elmerfem/pull/10) addressed to this issue. Please verify the result.

**Comment by pavelponomarev** [comment]
now works with --without-mumps . Thank you)
